spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
  application:
    name: employee-service
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  health:                        #Actuator endpoints for circuit breaker
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      employee-service:
        max-attempts: 5
        wait-duration: 1s


